/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mcDMfBAiTNTSdTh8zWvwGD
// Component: I5TSCwdYTog2
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: mcDMfBAiTNTSdTh8zWvwGD/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: mcDMfBAiTNTSdTh8zWvwGD/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: I5TSCwdYTog2/css
import OvalIcon from "./icons/PlasmicIcon__Oval"; // plasmic-import: u5otgK1cFrun/icon
import ChevronDown42Icon from "./icons/PlasmicIcon__ChevronDown42"; // plasmic-import: ZfkiheiGYM5V/icon
import ChevronDown4Icon from "./icons/PlasmicIcon__ChevronDown4"; // plasmic-import: A5cj5Ux9a4X4/icon

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"group1000003673"}
            data-plasmic-override={overrides.group1000003673}
            className={classNames(projectcss.all, sty.group1000003673)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___22NLe
              )}
            >
              {"Time to reimagine what you can do"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__x0J9E
              )}
            >
              {
                "Commodo condimentum est massa in enim fermentum. Mauris turpis et pellentesque."
              }
            </div>
            <div
              data-plasmic-name={"group1000003671"}
              data-plasmic-override={overrides.group1000003671}
              className={classNames(projectcss.all, sty.group1000003671)}
            >
              <div
                data-plasmic-name={"group1000003667"}
                data-plasmic-override={overrides.group1000003667}
                className={classNames(projectcss.all, sty.group1000003667)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vYkPm
                  )}
                >
                  {"Music"}
                </div>
                <div
                  data-plasmic-name={"rectangle32"}
                  data-plasmic-override={overrides.rectangle32}
                  className={classNames(projectcss.all, sty.rectangle32)}
                />

                <div
                  data-plasmic-name={"iconMusicCopy1"}
                  data-plasmic-override={overrides.iconMusicCopy1}
                  className={classNames(projectcss.all, sty.iconMusicCopy1)}
                />
              </div>
              <div
                data-plasmic-name={"group1000003668"}
                data-plasmic-override={overrides.group1000003668}
                className={classNames(projectcss.all, sty.group1000003668)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___31A3T
                  )}
                >
                  {"Art"}
                </div>
                <div
                  data-plasmic-name={"rectangle33"}
                  data-plasmic-override={overrides.rectangle33}
                  className={classNames(projectcss.all, sty.rectangle33)}
                />

                <div
                  data-plasmic-name={"iconArtCopy1"}
                  data-plasmic-override={overrides.iconArtCopy1}
                  className={classNames(projectcss.all, sty.iconArtCopy1)}
                />
              </div>
              <div
                data-plasmic-name={"group1000003669"}
                data-plasmic-override={overrides.group1000003669}
                className={classNames(projectcss.all, sty.group1000003669)}
              >
                <div
                  data-plasmic-name={"rectangle34"}
                  data-plasmic-override={overrides.rectangle34}
                  className={classNames(projectcss.all, sty.rectangle34)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__diHxW
                  )}
                >
                  {"Yoga"}
                </div>
                <div
                  data-plasmic-name={"iconYogaCopy1"}
                  data-plasmic-override={overrides.iconYogaCopy1}
                  className={classNames(projectcss.all, sty.iconYogaCopy1)}
                />
              </div>
              <div
                data-plasmic-name={"group1000003670"}
                data-plasmic-override={overrides.group1000003670}
                className={classNames(projectcss.all, sty.group1000003670)}
              >
                <div
                  data-plasmic-name={"rectangle30655"}
                  data-plasmic-override={overrides.rectangle30655}
                  className={classNames(projectcss.all, sty.rectangle30655)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__btVy8
                  )}
                >
                  {"Gym"}
                </div>
                <div
                  data-plasmic-name={"chatGptImageNov152025114017AmCopy1"}
                  data-plasmic-override={
                    overrides.chatGptImageNov152025114017AmCopy1
                  }
                  className={classNames(
                    projectcss.all,
                    sty.chatGptImageNov152025114017AmCopy1
                  )}
                />
              </div>
            </div>
            <div
              data-plasmic-name={"group2Copy"}
              data-plasmic-override={overrides.group2Copy}
              className={classNames(projectcss.all, sty.group2Copy)}
            >
              <OvalIcon
                className={classNames(projectcss.all, sty.svg__us7NC)}
                role={"img"}
              />

              <ChevronDown42Icon
                className={classNames(projectcss.all, sty.svg___4LDqW)}
                role={"img"}
              />
            </div>
            <div
              data-plasmic-name={"group2Copy2"}
              data-plasmic-override={overrides.group2Copy2}
              className={classNames(projectcss.all, sty.group2Copy2)}
            >
              <OvalIcon
                className={classNames(projectcss.all, sty.svg__wSbV8)}
                role={"img"}
              />

              <ChevronDown4Icon
                className={classNames(projectcss.all, sty.svg__bjfW)}
                role={"img"}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "group1000003673",
    "group1000003671",
    "group1000003667",
    "rectangle32",
    "iconMusicCopy1",
    "group1000003668",
    "rectangle33",
    "iconArtCopy1",
    "group1000003669",
    "rectangle34",
    "iconYogaCopy1",
    "group1000003670",
    "rectangle30655",
    "chatGptImageNov152025114017AmCopy1",
    "group2Copy",
    "group2Copy2"
  ],

  group1000003673: [
    "group1000003673",
    "group1000003671",
    "group1000003667",
    "rectangle32",
    "iconMusicCopy1",
    "group1000003668",
    "rectangle33",
    "iconArtCopy1",
    "group1000003669",
    "rectangle34",
    "iconYogaCopy1",
    "group1000003670",
    "rectangle30655",
    "chatGptImageNov152025114017AmCopy1",
    "group2Copy",
    "group2Copy2"
  ],

  group1000003671: [
    "group1000003671",
    "group1000003667",
    "rectangle32",
    "iconMusicCopy1",
    "group1000003668",
    "rectangle33",
    "iconArtCopy1",
    "group1000003669",
    "rectangle34",
    "iconYogaCopy1",
    "group1000003670",
    "rectangle30655",
    "chatGptImageNov152025114017AmCopy1"
  ],

  group1000003667: ["group1000003667", "rectangle32", "iconMusicCopy1"],
  rectangle32: ["rectangle32"],
  iconMusicCopy1: ["iconMusicCopy1"],
  group1000003668: ["group1000003668", "rectangle33", "iconArtCopy1"],
  rectangle33: ["rectangle33"],
  iconArtCopy1: ["iconArtCopy1"],
  group1000003669: ["group1000003669", "rectangle34", "iconYogaCopy1"],
  rectangle34: ["rectangle34"],
  iconYogaCopy1: ["iconYogaCopy1"],
  group1000003670: [
    "group1000003670",
    "rectangle30655",
    "chatGptImageNov152025114017AmCopy1"
  ],

  rectangle30655: ["rectangle30655"],
  chatGptImageNov152025114017AmCopy1: ["chatGptImageNov152025114017AmCopy1"],
  group2Copy: ["group2Copy"],
  group2Copy2: ["group2Copy2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    group1000003673: makeNodeComponent("group1000003673"),
    group1000003671: makeNodeComponent("group1000003671"),
    group1000003667: makeNodeComponent("group1000003667"),
    rectangle32: makeNodeComponent("rectangle32"),
    iconMusicCopy1: makeNodeComponent("iconMusicCopy1"),
    group1000003668: makeNodeComponent("group1000003668"),
    rectangle33: makeNodeComponent("rectangle33"),
    iconArtCopy1: makeNodeComponent("iconArtCopy1"),
    group1000003669: makeNodeComponent("group1000003669"),
    rectangle34: makeNodeComponent("rectangle34"),
    iconYogaCopy1: makeNodeComponent("iconYogaCopy1"),
    group1000003670: makeNodeComponent("group1000003670"),
    rectangle30655: makeNodeComponent("rectangle30655"),
    chatGptImageNov152025114017AmCopy1: makeNodeComponent(
      "chatGptImageNov152025114017AmCopy1"
    ),
    group2Copy: makeNodeComponent("group2Copy"),
    group2Copy2: makeNodeComponent("group2Copy2"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
