/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mcDMfBAiTNTSdTh8zWvwGD
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsf428PBZvfdv } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: f-428pBZvfdv/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsf428PBZvfdv
});
